### ISSUE TITLE
Supabase tables not updated

### ISSUE THREAD

**Issue by Selenuix** [PaddleHQ/paddle-nextjs-starter-kit#10]
### What happened?

Hi,

I followed the steps from the GH/docs but when I'm logged in and have an active subscription for that account, it doesn't show any subscription in the dashboard and the tables in supabase are empty.

The doc suggests that it should be filled, so I don't know if that's a bug or just an issue on my side.

I do get my customer, transaction and subscription in Paddle sandbox dashboard, with the correct data.

### Steps to reproduce

1. Deploy repo on vercel
2. Set up environment variables
3. Set up supabase project URL (from the default localhost:3000)
4. Create products
5. Update product IDs in code
6. Create an account
7. Subscribe to any product
8. Go to dashboard 

### What did you expect to happen?

The active subscription should show in the subscription tab and supabase tables shouldn't be empty.

**Comment by vijayasingam-paddle** [comment]
Hi @Selenuix, 

Sorry for the delay in getting back to you. Somehow, this has slipped through our fingers. 

Please let us know if you were able to solve the issue. If not, this should give you some pointers on what might be happening. 

Looking at your description, it appears to be a configuration issue related to the webhooks. 

We use the `customers` table to match the logged-in user's email address with the customer ID required to list subscriptions for that user. So if the `customers` table is empty, I am not surprised that you don't see any records even though your paddle dashboard shows all the data.

Two things could be happening here, 
- Your webhook configuration might be incorrect. Maybe you are not listening to the `customer.created`, `customer.updated`, `subscription.created` and `subscription.updated` events?  You can check this by logging into the dashboard and navigating to the `Notifications` screen under `Developer Tools`.

 - Your webhook secret is incorrect and signature verification is failing. You can check your vercel logs to identify this.

Please let us know if this helped or share some more information so that we can help you further. 

Thank you.

**Comment by danbillson** [comment]
@Selenuix @jonny07 there was a change in how anonymous logins through supabase work, which doesn't tie an email to a user until the email has been verified. Since we get the Paddle customer ID by the logged in user email, this will no longer work since there is no email to compare against. In the meantime can you check if your implementation works using email and password with a verified email or third-party auth, if it is still not working, I am happy to provide additional debugging steps.

We will continue to investigate how best to handle anonymous auth.

**Comment by jonny07** [comment]
It is not anonymous, I sign up with email and password, confirm the email and then sign in!!

**Comment by danbillson** [comment]
@jonny07 If you are not seeing any payments or subscription data after creating an account, verifying the email and making a purchase on the account, this would suggest an issue with setting up the webhooks. Some things to double-check are:
- Ensure the webhook destination is set correctly in Paddle to the deployed app i.e. `https://your-starter-kit.vercel.app/api/webhook`
- Check that the notification settings are set to Webhook, are for platform usage and have all of the required events enabled
- Check that you are using the correct webhook secret that is prefixed with `pdl_ntfset_`

![Image](https://github.com/user-attachments/assets/ea466a31-7ca5-42b8-995d-09f3f3ee2ea8)

If everything is configured correctly, you can see the requests to `/api/webhook` in the vercel logs. If the requests are being made but still not working, you can add some additional logging to the request handler to debug the issue further.

![Image](https://github.com/user-attachments/assets/ff711fa8-72fb-429d-a098-95903f300f6f)

**Comment by jonny07** [comment]
I did all that. Just reproduce as I wrote, it is not working. Don't know what else to say. And as stated above already the webhooks work. I TESTED THAT ALREADY. The problem is as I wrote several times that 1. there is no entry in supabase database after sign up und 2. the header is not accepted as described in detail above, which i could only figure out through debugging and adding logging. But I can not correct it as it's somewhere deep in your libraries.

**Comment by danbillson** [comment]
> 1. there is no entry in supabase database after sign up
The supabase auth entry and paddle customer are two separate things. Creating an account will create a supabase auth entry, *not* a customer record in the database. When you go through the checkout and make a payment, that is when the customer will be created which is linked to the supabase auth entry by email address.
If you are experiencing issues with data not correctly being added to the database, this may suggest that the database is out of sync with Paddle's data, such as a missing customer record in your database, which will need to be resolved.

> 2. the header is not accepted as described in detail above
Do you have a deployed site that we would be able to investigate?

**Comment by jonny07** [comment]
Thank you for your feedback. My website is www.davincidreams.com. I deleted the databases again and signed up with new email. The entries in the database are present now. However still subscriptions and payments are empty. 

For debugging I changed get-subscriptions.ts as follows:

'use server';

import { getCustomerId } from '@/utils/paddle/get-customer-id';
import { getPaddleInstance } from '@/utils/paddle/get-paddle-instance';
import { SubscriptionResponse } from '@/lib/api.types';
import { getErrorMessage } from '@/utils/paddle/data-helpers';

export async function getSubscriptions(): Promise<SubscriptionResponse> {
  try {
    console.log('getSubscriptions: Starting to fetch subscriptions.');
    const customerId = await getCustomerId();
    if (customerId) {
      console.log(`getSubscriptions: Customer ID found: ${customerId}. Fetching subscriptions.`);
      const subscriptionCollection = getPaddleInstance().subscriptions.list({ customerId: [customerId], perPage: 20 });
      const subscriptions = await subscriptionCollection.next();
      console.log('getSubscriptions: Subscriptions fetched successfully.');
      return {
        data: subscriptions,
        hasMore: subscriptionCollection.hasMore,
        totalRecords: subscriptionCollection.estimatedTotal,
      };
    } else {
      console.log('getSubscriptions: Customer ID not found.');
    }
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
  } catch (e) {
    console.error('getSubscriptions: Error fetching subscriptions:', e);
    return getErrorMessage();
  }
  console.log('getSubscriptions: Returning error due to missing customer ID or other issue.');
  return getErrorMessage();
}

This is the log:

getSubscriptions: Starting to fetch subscriptions.
getCustomerId - User Data: {
  data: {
    user: {
      id: 'db8328d5-9338-4d29-9c33-3c8e5e4329a7',
      aud: 'authenticated',
      role: 'authenticated',
      email: 'johannes.jaegers@gmx.de',
      email_confirmed_at: '2025-03-07T11:56:05.860168Z',
      phone: '',
      confirmation_sent_at: '2025-03-07T11:55:32.054003Z',
      confirmed_at: '2025-03-07T11:56:05.860168Z',
      last_sign_in_at: '2025-03-07T11:57:07.160362Z',
      app_metadata: [Object],
      user_metadata: [Object],
      identities: [Array],
      created_at: '2025-03-07T11:55:32.010873Z',
      updated_at: '2025-03-07T11:57:07.172205Z',
      is_anonymous: false
    }
  },
  error: null
}
getCustomerId - User Email: johannes.jaegers@gmx.de
getCustomerId - Customers Data: {
  error: null,
  data: {
    customer_id: 'ctm_01jnr7f6yzkcwj335j3914gepe',
    email: 'johannes.jaegers@gmx.de'
  },
  count: null,
  status: 200,
  statusText: 'OK'
}
getCustomerId - Found Customer ID: ctm_01jnr7f6yzkcwj335j3914gepe
getSubscriptions: Customer ID found: ctm_01jnr7f6yzkcwj335j3914gepe. Fetching subscriptions.
getSubscriptions: Error fetching subscriptions: Error: Authentication header included, but incorrectly formatted.
    at tv.handlePaginatedResponse (.next/server/chunks/829.js:1:4991)
    at tv.i (.next/server/chunks/829.js:1:4393)
    at i.next (<anonymous>)
    at a (.next/server/chunks/829.js:1:4742) {
  type: 'request_error',
  code: 'authentication_malformed',
  detail: 'Authentication header included, but incorrectly formatted.',
  documentationUrl: 'https://developer.paddle.com/v1/errors/shared/authentication_malformed',
  errors: null
}


I did not debug the payment further, the error I get is:
Something went wrong, please try again later.

**Comment by danbillson** [comment]
@jonny07 Thanks for the detailed trace, this looks like it is an issue with the API key, can you confirm that your `PADDLE_API_KEY` is a 50 character alphanumeric value that is not prefixed with `live_` or `test_`, you can check your keys in the [authentication page](https://vendors.paddle.com/authentication-v2) in the **API Keys** table

**Comment by jonny07** [comment]
PADDLE_API_KEY=f0555d5b5553ggb9d666a1z8a07b7a5jj777f44455ezzze49f
this is my key, i changed characters here

**Comment by danbillson** [comment]
Okay great, and then just checking that the `NEXT_PUBLIC_PADDLE_ENV` matches the right key.

If you're using `sandbox`, the key should show in https://sandbox-vendors.paddle.com/authentication-v2
Otherwise if you're using `production` it should be from https://vendors.paddle.com/authentication-v2

**Comment by jonny07** [comment]
# Paddle
## Private
NEXT_PUBLIC_PADDLE_ENV=sandbox # or `production`

I just left it as was and using sandbox

**Comment by jonny07** [comment]
So any update? It is not working as described above.

**Comment by vijayasingam-paddle** [comment]
Hi @jonny07, 
Sorry for the delay in responding to you. 

I tried reproducing this issue with the latest code and your API key. Everything worked for me, which makes me wonder if there is a typo somewhere in your configuration. 

The error message you are getting also represents that a value was sent for the API key, however it is incorrect.

These are the env variables that worked for me, 
PADDLE_API_KEY=f058***
NEXT_PUBLIC_PADDLE_ENV=sandbox
NEXT_PUBLIC_PADDLE_CLIENT_TOKEN=test_1***

Additionally, can you also please double-check if the configured values are passed down correctly while creating `Paddle` instance here(`src/utils/paddle/get-paddle-instance.ts`)

Thank you.

**Comment by vijayasingam-paddle** [comment]
Hi @Selenuix,
Thank you for getting back to us. 

Logging into the system before subscribing is not relevant for updating supabase tables. Any completed checkout will trigger webhook events and should be stored in the tables. 

From your description, it seems like that is not happening. Can you please check your supabase logs to see if there are any errors? 

I am wondering if the webhook secret is incorrect.

Please share some logs so that we can help you further.

Thank you.

**Comment by maciejb7** [comment]
Hi, I believe your issue may occur as the `customer.created` event is triggered only the first time a customer makes a transaction. You can verify whether the `customer.created` event was delivered successfully by checking the Notification logs in the Paddle dashboard. 

If for any reason during the customer's first transaction a new row wasn't created in your `public.customers` table (for example, a Supabase migration was not ran yet, Supabase env variables were not configured etc.), an exact issue described will occur - Paddle will process the transactions successfully, however, the acquired subscription won't be inserted in the `public.subscriptions` table because of the constraint violation:

```
{
  code: '23503',
  details: 'Key (customer_id)=(ctm_XXX) is not present in table "customers".',
  hint: null,
  message: 'insert or update on table "subscriptions" violates foreign key constraint "public_subscriptions_customer_id_fkey"'
}
```


In that case, as both `public.customers` and `public.subscriptions` tables were not populated, the customer's subscription will not show up in the dashboard. Therefore, in order to test the deployment, make sure you are using a test email that has not made a transaction that was recorded by Paddle yet (i.e., triggered a `customer.created` event without creating a database entry). 

Hope that helps!

**Comment by mshehrozsajjad** [comment]
This issue happened for me as well. I think because I skipped supabase seed option or running supabase migration is necessary and it is not mentioned in the docs. After running migration everything was working.

**Comment by vijayasingam-paddle** [comment]
Hi @mshehrozsajjad,

Thank you for the update. We will improve the documentation to include some details about the migration script and how to run if the project was created without it. 

Thank you.
